### ISSUE TITLE
Titan Ridge v2

### ISSUE THREAD

**Issue by xxx31fr** [ameyrupji/thunderbolt-macpro-5-1#3]
Hello, can you say me if i can upgrade firmware for Titan Ridge v2 with your method?

thanks.

on the Titan Ridge v2, there is no power pin.

**Comment by ameyrupji** [comment]
sorry, I don't understand what you mean by Titan Ridge v2. Do you mean rev.2.0, if yes I don't know. My card is rev.1.0. Try it out or check with the broader community if they have any luck! 

If possible please inform me so that I can update this with the information you provide!


Comparing at the documentation online 
https://www.gigabyte.com/us/Motherboard/GC-TITAN-RIDGE-rev-10#kf
https://www.gigabyte.com/us/Motherboard/GC-TITAN-RIDGE-rev-20#kf

There is definitely a difference in the official boards that they support.
